# Generated by Django 5.0.3 on 2024-04-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('full_time', 'full_time'), ('part_time', 'part_time')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
