# Generated by Django 5.0.3 on 2024-04-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('full_time', 'fulltime'), ('part_time', 'part_time')], max_length=10),
        ),
    ]
